EXPORT float b2_mix_friction(float friction1, float friction2);
EXPORT float b2_mix_restitution(float restitution1, float restitution2);
EXPORT float b2_mix_restitution_threshold(float threshold1, float threshold2);
EXPORT b2Manifold* Contact_get_manifold(b2Contact* self);
EXPORT void Contact_get_world_manifold(b2Contact* self, b2WorldManifold* worldManifold);
EXPORT bool Contact_is_touching(b2Contact* self);
EXPORT void Contact_set_enabled(b2Contact* self, bool flag);
EXPORT bool Contact_is_enabled(b2Contact* self);
EXPORT b2Contact* Contact_get_next(b2Contact* self);
EXPORT b2Fixture* Contact_get_fixture_a(b2Contact* self);
EXPORT int32 Contact_get_child_index_a(b2Contact* self);
EXPORT b2Fixture* Contact_get_fixture_b(b2Contact* self);
EXPORT int32 Contact_get_child_index_b(b2Contact* self);
EXPORT void Contact_set_friction(b2Contact* self, float friction);
EXPORT float Contact_get_friction(b2Contact* self);
EXPORT void Contact_reset_friction(b2Contact* self);
EXPORT void Contact_set_restitution(b2Contact* self, float restitution);
EXPORT float Contact_get_restitution(b2Contact* self);
EXPORT void Contact_reset_restitution(b2Contact* self);
EXPORT void Contact_set_restitution_threshold(b2Contact* self, float threshold);
EXPORT float Contact_get_restitution_threshold(b2Contact* self);
EXPORT void Contact_reset_restitution_threshold(b2Contact* self);
EXPORT void Contact_set_tangent_speed(b2Contact* self, float speed);
EXPORT float Contact_get_tangent_speed(b2Contact* self);
EXPORT void Contact_evaluate(b2Contact* self, b2Manifold* manifold, const b2Transform* xfA, const b2Transform* xfB);