EXPORT b2Filter* Filter_new();
EXPORT b2Filter Filter_create();
EXPORT b2FixtureDef* FixtureDef_new();
EXPORT b2FixtureDef FixtureDef_create();
EXPORT b2Shape::Type Fixture_get_type(b2Fixture* self);
EXPORT b2Shape* Fixture_get_shape(b2Fixture* self);
EXPORT void Fixture_set_sensor(b2Fixture* self, bool flag);
EXPORT bool Fixture_is_sensor(b2Fixture* self);
EXPORT void Fixture_set_filter_data(b2Fixture* self, const b2Filter* filter);
EXPORT b2Filter Fixture_get_filter_data(b2Fixture* self);
EXPORT void Fixture_refilter(b2Fixture* self);
EXPORT b2Body* Fixture_get_body(b2Fixture* self);
EXPORT b2Fixture* Fixture_get_next(b2Fixture* self);
EXPORT void* Fixture_get_user_data(b2Fixture* self);
EXPORT void Fixture_set_user_data(b2Fixture* self, void* data);
EXPORT bool Fixture_test_point(b2Fixture* self, const b2Vec2* p);
EXPORT void Fixture_compute_distance(b2Fixture* self, const b2Vec2* p, float32* distance, b2Vec2* normal, int32 childIndex);
EXPORT bool Fixture_ray_cast(b2Fixture* self, b2RayCastOutput* output, const b2RayCastInput* input, int32_t child_id);
EXPORT void Fixture_get_mass_data(b2Fixture* self, b2MassData* data);
EXPORT void Fixture_set_density(b2Fixture* self, float density);
EXPORT float Fixture_get_density(b2Fixture* self);
EXPORT float Fixture_get_friction(b2Fixture* self);
EXPORT void Fixture_set_friction(b2Fixture* self, float friction);
EXPORT float Fixture_get_restitution(b2Fixture* self);
EXPORT void Fixture_set_restitution(b2Fixture* self, float restitution);
EXPORT float Fixture_get_restitution_threshold(b2Fixture* self);
EXPORT void Fixture_set_restitution_threshold(b2Fixture* self, float threshold);
EXPORT const b2AABB* Fixture_get_aabb(b2Fixture* self, int32_t childIndex);
EXPORT void Fixture_dump(b2Fixture* self, int32_t bodyIndex);