EXPORT b2World* World_new(const b2Vec2 gravity);
EXPORT b2World World_create(const b2Vec2 gravity);
EXPORT void World_set_destruction_listener(b2World* self, b2DestructionListener* listener);
EXPORT void World_set_contact_filter(b2World* self, b2ContactFilter* filter);
EXPORT void World_set_contact_listener(b2World* self, b2ContactListener* listener);
EXPORT void World_set_debug_draw(b2World* self, b2Draw* debugDraw);
EXPORT b2Body* World_create_body(b2World* self, const b2BodyDef* def);
EXPORT void World_destroy_body(b2World* self, b2Body* body);
EXPORT b2Joint* World_create_joint(b2World* self, const b2JointDef* def);
EXPORT void World_destroy_joint(b2World* self, b2Joint* joint);
EXPORT b2ParticleSystem* World_create_particle_system(b2World* self, const b2ParticleSystemDef* def);
EXPORT void World_destroy_particle_system(b2World* self, b2ParticleSystem* p);
EXPORT void World_step(b2World* self, float timeStep, int32_t velocityIterations, int32_t positionIterations, int32_t particleIterations);
EXPORT int World_calculate_reasonable_particle_iterations(b2World* self, float32 timeStep);
EXPORT void World_clear_forces(b2World* self);
EXPORT void World_debug_draw(b2World* self);
EXPORT void World_query_aabb(b2World* self, b2QueryCallback* callback, const b2AABB* aabb);
EXPORT void World_query_shape_aabb(b2World* self, b2QueryCallback* callback, const b2Shape* shape, const b2Transform* xf);
EXPORT void World_ray_cast(b2World* self, b2RayCastCallback* callback, const b2Vec2* p1, const b2Vec2* p2);
EXPORT b2Body* World_get_body_list(b2World* self);
EXPORT b2Joint* World_get_joint_list(b2World* self);
EXPORT b2ParticleSystem* World_get_particle_system_list(b2World* self);
EXPORT b2Contact* World_get_contact_list(b2World* self);
EXPORT void World_set_allow_sleeping(b2World* self, bool flag);
EXPORT bool World_get_allow_sleeping(b2World* self);
EXPORT void World_set_warm_starting(b2World* self, bool flag);
EXPORT bool World_get_warm_starting(b2World* self);
EXPORT void World_set_continuous_physics(b2World* self, bool flag);
EXPORT bool World_get_continuous_physics(b2World* self);
EXPORT void World_set_sub_stepping(b2World* self, bool flag);
EXPORT bool World_get_sub_stepping(b2World* self);
EXPORT int32_t World_get_proxy_count(b2World* self);
EXPORT int32_t World_get_body_count(b2World* self);
EXPORT int32_t World_get_joint_count(b2World* self);
EXPORT int32_t World_get_contact_count(b2World* self);
EXPORT int32_t World_get_tree_height(b2World* self);
EXPORT int32_t World_get_tree_balance(b2World* self);
EXPORT float World_get_tree_quality(b2World* self);
EXPORT void World_set_gravity(b2World* self, const b2Vec2* gravity);
EXPORT b2Vec2 World_get_gravity(b2World* self);
EXPORT bool World_is_locked(b2World* self);
EXPORT void World_set_auto_clear_forces(b2World* self, bool flag);
EXPORT bool World_get_auto_clear_forces(b2World* self);
EXPORT void World_shift_origin(b2World* self, const b2Vec2* origin);
EXPORT b2ContactManager World_get_contact_manager(b2World* self);
EXPORT b2Profile World_get_profile(b2World* self);
EXPORT void World_dump(b2World* self);

// TODO replace all const something* with just something