EXPORT b2FrictionJointDef* FrictionJointDef_new();
EXPORT b2FrictionJointDef FrictionJointDef_create();
EXPORT void FrictionJointDef_initialize(b2FrictionJointDef* self, b2Body* bodyA, b2Body* bodyB, const b2Vec2* anchor);
EXPORT b2Vec2 FrictionJoint_get_anchor_a(b2FrictionJoint* self);
EXPORT b2Vec2 FrictionJoint_get_anchor_b(b2FrictionJoint* self);
EXPORT b2Vec2 FrictionJoint_get_reaction_force(b2FrictionJoint* self, float inv_dt);
EXPORT float FrictionJoint_get_reaction_torque(b2FrictionJoint* self, float inv_dt);
EXPORT b2Vec2 FrictionJoint_get_local_anchor_a(b2FrictionJoint* self);
EXPORT b2Vec2 FrictionJoint_get_local_anchor_b(b2FrictionJoint* self);
EXPORT void FrictionJoint_set_max_force(b2FrictionJoint* self, float force);
EXPORT float FrictionJoint_get_max_force(b2FrictionJoint* self);
EXPORT void FrictionJoint_set_max_torque(b2FrictionJoint* self, float torque);
EXPORT float FrictionJoint_get_max_torque(b2FrictionJoint* self);
EXPORT void FrictionJoint_dump(b2FrictionJoint* self);