EXPORT b2GearJointDef* GearJointDef_new();
EXPORT b2GearJointDef GearJointDef_create();
EXPORT b2Vec2 GearJoint_get_anchor_a(b2GearJoint* self);
EXPORT b2Vec2 GearJoint_get_anchor_b(b2GearJoint* self);
EXPORT b2Vec2 GearJoint_get_reaction_force(b2GearJoint* self, float inv_dt);
EXPORT float GearJoint_get_reaction_torque(b2GearJoint* self, float inv_dt);
EXPORT b2Joint* GearJoint_get_joint1(b2GearJoint* self);
EXPORT b2Joint* GearJoint_get_joint2(b2GearJoint* self);
EXPORT void GearJoint_set_ratio(b2GearJoint* self, float ratio);
EXPORT float GearJoint_get_ratio(b2GearJoint* self);
EXPORT void GearJoint_dump(b2GearJoint* self);