EXPORT b2MotorJointDef* MotorJointDef_new();
EXPORT b2MotorJointDef MotorJointDef_create();
EXPORT void MotorJointDef_initialize(b2MotorJointDef* self, b2Body* bodyA, b2Body* bodyB);
EXPORT b2Vec2 MotorJoint_get_anchor_a(b2MotorJoint* self);
EXPORT b2Vec2 MotorJoint_get_anchor_b(b2MotorJoint* self);
EXPORT b2Vec2 MotorJoint_get_reaction_force(b2MotorJoint* self, float inv_dt);
EXPORT float MotorJoint_get_reaction_torque(b2MotorJoint* self, float inv_dt);
EXPORT void MotorJoint_set_linear_offset(b2MotorJoint* self, const b2Vec2* linearOffset);
EXPORT b2Vec2 MotorJoint_get_linear_offset(b2MotorJoint* self);
EXPORT void MotorJoint_set_angular_offset(b2MotorJoint* self, float angularOffset);
EXPORT float MotorJoint_get_angular_offset(b2MotorJoint* self);
EXPORT void MotorJoint_set_max_force(b2MotorJoint* self, float force);
EXPORT float MotorJoint_get_max_force(b2MotorJoint* self);
EXPORT void MotorJoint_set_max_torque(b2MotorJoint* self, float torque);
EXPORT float MotorJoint_get_max_torque(b2MotorJoint* self);
EXPORT void MotorJoint_set_correction_factor(b2MotorJoint* self, float factor);
EXPORT float MotorJoint_get_correction_factor(b2MotorJoint* self);
EXPORT void MotorJoint_dump(b2MotorJoint* self);