EXPORT b2PrismaticJointDef* PrismaticJointDef_new();
EXPORT b2PrismaticJointDef PrismaticJointDef_create();
EXPORT void PrismaticJointDef_initialize(b2PrismaticJointDef* self, b2Body* bodyA, b2Body* bodyB, const b2Vec2* anchor, const b2Vec2* axis);
EXPORT b2Vec2 PrismaticJoint_get_anchor_a(b2PrismaticJoint* self);
EXPORT b2Vec2 PrismaticJoint_get_anchor_b(b2PrismaticJoint* self);
EXPORT b2Vec2 PrismaticJoint_get_reaction_force(b2PrismaticJoint* self, float inv_dt);
EXPORT float PrismaticJoint_get_reaction_torque(b2PrismaticJoint* self, float inv_dt);
EXPORT b2Vec2 PrismaticJoint_get_local_anchor_a(b2PrismaticJoint* self);
EXPORT b2Vec2 PrismaticJoint_get_local_anchor_b(b2PrismaticJoint* self);
EXPORT b2Vec2 PrismaticJoint_get_local_axis_a(b2PrismaticJoint* self);
EXPORT float PrismaticJoint_get_reference_angle(b2PrismaticJoint* self);
EXPORT float PrismaticJoint_get_joint_translation(b2PrismaticJoint* self);
EXPORT float PrismaticJoint_get_joint_speed(b2PrismaticJoint* self);
EXPORT bool PrismaticJoint_is_limit_enabled(b2PrismaticJoint* self);
EXPORT void PrismaticJoint_enable_limit(b2PrismaticJoint* self, bool flag);
EXPORT float PrismaticJoint_get_lower_limit(b2PrismaticJoint* self);
EXPORT float PrismaticJoint_get_upper_limit(b2PrismaticJoint* self);
EXPORT void PrismaticJoint_set_limits(b2PrismaticJoint* self, float lower, float upper);
EXPORT bool PrismaticJoint_is_motor_enabled(b2PrismaticJoint* self);
EXPORT void PrismaticJoint_enable_motor(b2PrismaticJoint* self, bool flag);
EXPORT void PrismaticJoint_set_motor_speed(b2PrismaticJoint* self, float speed);
EXPORT float PrismaticJoint_get_motor_speed(b2PrismaticJoint* self);
EXPORT void PrismaticJoint_set_max_motor_force(b2PrismaticJoint* self, float force);
EXPORT float PrismaticJoint_get_max_motor_force(b2PrismaticJoint* self);
EXPORT float PrismaticJoint_get_motor_force(b2PrismaticJoint* self, float inv_dt);
EXPORT void PrismaticJoint_dump(b2PrismaticJoint* self);
EXPORT void PrismaticJoint_draw(b2PrismaticJoint* self, b2Draw* draw);