EXPORT b2PulleyJointDef* PulleyJointDef_new();
EXPORT b2PulleyJointDef PulleyJointDef_create();
EXPORT void PulleyJointDef_initialize(b2PulleyJointDef* self, b2Body* bodyA, b2Body* bodyB, const b2Vec2* groundAnchorA, const b2Vec2* groundAnchorB, const b2Vec2* anchorA, const b2Vec2* anchorB, float ratio);
EXPORT b2Vec2 PulleyJoint_get_anchor_a(b2PulleyJoint* self);
EXPORT b2Vec2 PulleyJoint_get_anchor_b(b2PulleyJoint* self);
EXPORT b2Vec2 PulleyJoint_get_reaction_force(b2PulleyJoint* self, float inv_dt);
EXPORT float PulleyJoint_get_reaction_torque(b2PulleyJoint* self, float inv_dt);
EXPORT b2Vec2 PulleyJoint_get_ground_anchor_a(b2PulleyJoint* self);
EXPORT b2Vec2 PulleyJoint_get_ground_anchor_b(b2PulleyJoint* self);
EXPORT float PulleyJoint_get_length_a(b2PulleyJoint* self);
EXPORT float PulleyJoint_get_length_b(b2PulleyJoint* self);
EXPORT float PulleyJoint_get_ratio(b2PulleyJoint* self);
EXPORT float PulleyJoint_get_current_length_a(b2PulleyJoint* self);
EXPORT float PulleyJoint_get_current_length_b(b2PulleyJoint* self);
EXPORT void PulleyJoint_dump(b2PulleyJoint* self);
EXPORT void PulleyJoint_shift_origin(b2PulleyJoint* self, const b2Vec2* newOrigin);