EXPORT b2RevoluteJointDef* RevoluteJointDef_new();
EXPORT b2RevoluteJointDef RevoluteJointDef_create();
EXPORT void RevoluteJointDef_initialize(b2RevoluteJointDef* self, b2Body* bodyA, b2Body* bodyB, const b2Vec2* anchor);
EXPORT b2Vec2 RevoluteJoint_get_anchor_a(b2RevoluteJoint* self);
EXPORT b2Vec2 RevoluteJoint_get_anchor_b(b2RevoluteJoint* self);
EXPORT b2Vec2 RevoluteJoint_get_local_anchor_a(b2RevoluteJoint* self);
EXPORT b2Vec2 RevoluteJoint_get_local_anchor_b(b2RevoluteJoint* self);
EXPORT float RevoluteJoint_get_reference_angle(b2RevoluteJoint* self);
EXPORT float RevoluteJoint_get_joint_angle(b2RevoluteJoint* self);
EXPORT float RevoluteJoint_get_joint_speed(b2RevoluteJoint* self);
EXPORT bool RevoluteJoint_is_limit_enabled(b2RevoluteJoint* self);
EXPORT void RevoluteJoint_enable_limit(b2RevoluteJoint* self, bool flag);
EXPORT float RevoluteJoint_get_lower_limit(b2RevoluteJoint* self);
EXPORT float RevoluteJoint_get_upper_limit(b2RevoluteJoint* self);
EXPORT void RevoluteJoint_set_limits(b2RevoluteJoint* self, float lower, float upper);
EXPORT bool RevoluteJoint_is_motor_enabled(b2RevoluteJoint* self);
EXPORT void RevoluteJoint_enable_motor(b2RevoluteJoint* self, bool flag);
EXPORT void RevoluteJoint_set_motor_speed(b2RevoluteJoint* self, float speed);
EXPORT float RevoluteJoint_get_motor_speed(b2RevoluteJoint* self);
EXPORT void RevoluteJoint_set_max_motor_torque(b2RevoluteJoint* self, float torque);
EXPORT float RevoluteJoint_get_max_motor_torque(b2RevoluteJoint* self);
EXPORT b2Vec2 RevoluteJoint_get_reaction_force(b2RevoluteJoint* self, float inv_dt);
EXPORT float RevoluteJoint_get_reaction_torque(b2RevoluteJoint* self, float inv_dt);
EXPORT float RevoluteJoint_get_motor_torque(b2RevoluteJoint* self, float inv_dt);
EXPORT void RevoluteJoint_dump(b2RevoluteJoint* self);
EXPORT void RevoluteJoint_draw(b2RevoluteJoint* self, b2Draw* draw);