EXPORT b2RopeTuning* RopeTuning_new();
EXPORT b2RopeTuning RopeTurning_create();
EXPORT b2RopeDef* RopeDef_new();
EXPORT b2RopeDef RopeDef_create();
EXPORT b2Rope* Rope_new();
EXPORT b2Rope Rope_create();
EXPORT void Rope_initialize(b2Rope* self, const b2RopeDef* def);
EXPORT void Rope_set_tuning(b2Rope* self, const b2RopeTuning* tuning);
EXPORT void Rope_step(b2Rope* self, float timeStep, int32_t iterations, const b2Vec2* position);
EXPORT void Rope_reset(b2Rope* self, const b2Vec2* position);
EXPORT void Rope_draw(b2Rope* self, b2Draw* draw);