EXPORT b2WeldJointDef* WeldJointDef_new();
EXPORT b2WeldJointDef WeldJointDef_create();
EXPORT void WeldJointDef_initialize(b2WeldJointDef* self, b2Body* bodyA, b2Body* bodyB, const b2Vec2* anchor);
EXPORT b2Vec2 WeldJoint_get_anchor_a(b2WeldJoint* self);
EXPORT b2Vec2 WeldJoint_get_anchor_b(b2WeldJoint* self);
EXPORT b2Vec2 WeldJoint_get_reaction_force(b2WeldJoint* self, float inv_dt);
EXPORT float WeldJoint_get_reaction_torque(b2WeldJoint* self, float inv_dt);
EXPORT b2Vec2 WeldJoint_get_local_anchor_a(b2WeldJoint* self);
EXPORT b2Vec2 WeldJoint_get_local_anchor_b(b2WeldJoint* self);
EXPORT float WeldJoint_get_reference_angle(b2WeldJoint* self);
EXPORT void WeldJoint_set_stiffness(b2WeldJoint* self, float stiffness);
EXPORT float WeldJoint_get_stiffness(b2WeldJoint* self);
EXPORT void WeldJoint_set_damping(b2WeldJoint* self, float damping);
EXPORT float WeldJoint_get_damping(b2WeldJoint* self);
EXPORT void WeldJoint_dump(b2WeldJoint* self);