EXPORT b2WheelJointDef* WheelJointDef_new();
EXPORT b2WheelJointDef WheelJointDef_create();
EXPORT void WheelJointDef_initialize(b2WheelJointDef* self, b2Body* bodyA, b2Body* bodyB, const b2Vec2* anchor, const b2Vec2* axis);
EXPORT b2Vec2 WheelJoint_get_anchor_a(b2WheelJoint* self);
EXPORT b2Vec2 WheelJoint_get_anchor_b(b2WheelJoint* self);
EXPORT b2Vec2 WheelJoint_get_reaction_force(b2WheelJoint* self, float inv_dt);
EXPORT float WheelJoint_get_reaction_torque(b2WheelJoint* self, float inv_dt);
EXPORT b2Vec2 WheelJoint_get_local_anchor_a(b2WheelJoint* self);
EXPORT b2Vec2 WheelJoint_get_local_anchor_b(b2WheelJoint* self);
EXPORT b2Vec2 WheelJoint_get_local_axis_a(b2WheelJoint* self);
EXPORT float WheelJoint_get_joint_translation(b2WheelJoint* self);
EXPORT float WheelJoint_get_joint_linear_speed(b2WheelJoint* self);
EXPORT float WheelJoint_get_joint_angle(b2WheelJoint* self);
EXPORT float WheelJoint_get_joint_angular_speed(b2WheelJoint* self);
EXPORT bool WheelJoint_is_limit_enabled(b2WheelJoint* self);
EXPORT void WheelJoint_enable_limit(b2WheelJoint* self, bool flag);
EXPORT float WheelJoint_get_lower_limit(b2WheelJoint* self);
EXPORT float WheelJoint_get_upper_limit(b2WheelJoint* self);
EXPORT void WheelJoint_set_limits(b2WheelJoint* self, float lower, float upper);
EXPORT bool WheelJoint_is_motor_enabled(b2WheelJoint* self);
EXPORT void WheelJoint_enable_motor(b2WheelJoint* self, bool flag);
EXPORT void WheelJoint_set_motor_speed(b2WheelJoint* self, float speed);
EXPORT float WheelJoint_get_motor_speed(b2WheelJoint* self);
EXPORT void WheelJoint_set_max_motor_torque(b2WheelJoint* self, float torque);
EXPORT float WheelJoint_get_max_motor_torque(b2WheelJoint* self);
EXPORT float WheelJoint_get_motor_torque(b2WheelJoint* self, float inv_dt);
EXPORT void WheelJoint_set_stiffness(b2WheelJoint* self, float stiffness);
EXPORT float WheelJoint_get_stiffness(b2WheelJoint* self);
EXPORT void WheelJoint_set_damping(b2WheelJoint* self, float damping);
EXPORT float WheelJoint_get_damping(b2WheelJoint* self);
EXPORT void WheelJoint_dump(b2WheelJoint* self);
EXPORT void WheelJoint_draw(b2WheelJoint* self, b2Draw* draw);